<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>DoubleCorvid's NEST - Settings</Title>
    <Version>0.4.0-ALPHA</Version>
    <Authors>DoubleCorvid</Authors>
    <Company />
    <Description>Settings framework for NEST.</Description>
    <Copyright>Copyright © Raven Crowe 2026</Copyright>
    <PackageProjectUrl>https://github.com/ravencrowe01/DoubleCorvid.NEST</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ravencrowe01/DoubleCorvid.NEST</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DoubleCorvid.Grimoire.Files" Version="0.17.1-ALPHA" />
    <PackageReference Include="DoubleCorvid.Grimoire.Settings" Version="0.17.1-ALPHA" />
  </ItemGroup>

</Project>
